### PR TITLE
Update ProjectsTagsStable.cmake in order to set yarp-3.10 as stable branch and use YARP 3.10 releases in LatestReleases

### PR DESCRIPTION
**Pull request by Nicogene**
As per title

cc @pattacini

### CODE REVIEW

**Comment by traversaro** [comment]
Thanks! I think we can also bump the latest releases of yarp to 3.10.1 and yarp-matlab-bindings to 3.10.0 .

**Comment by traversaro** [comment]
This PR fixes https://github.com/robotology/robotology-superbuild/issues/1740 .

**Comment by Nicogene** [comment]
> Thanks! I think we can also bump the latest releases of yarp to 3.10.1 and yarp-matlab-bindings to 3.10.0 .

Done!

**Comment by traversaro** [comment]
> The CI fails. This make sense as we now need to always build the `yarp-ros` repo.

This should be fixed by https://github.com/robotology/robotology-superbuild/commit/b0666ce507f82a0523adc25ea6cf8b484df25517 .

**Review by traversaro — APPROVED** [review]
Approving, but we need to wait for CI to be green before merging.

**Comment by traversaro** [comment]
New failures:

~~~
2024-11-27T17:33:39.5384573Z --  [x] Plugin: ftshoe (ENABLE_ftshoe)
2024-11-27T17:33:39.5385067Z --  [ ] Plugin: ftShoeUdpWrapper (ENABLE_ftShoeUdpWrapper)
2024-11-27T17:33:39.5385558Z -- Configuring done (3.2s)
2024-11-27T17:33:39.5385927Z -- Generating done (0.2s)
2024-11-27T17:33:39.5386840Z -- Build files have been written to: /home/runner/work/robotology-superbuild/robotology-superbuild/build/src/yarp-devices-forcetorque
2024-11-27T17:33:54.4271633Z [407/504] Performing build step for 'yarp-devices-forcetorque'
2024-11-27T17:33:54.4274012Z FAILED: src/yarp-devices-forcetorque/CMakeFiles/YCMStamp/yarp-devices-forcetorque-build /home/runner/work/robotology-superbuild/robotology-superbuild/build/src/yarp-devices-forcetorque/CMakeFiles/YCMStamp/yarp-devices-forcetorque-build 
2024-11-27T17:33:54.4277120Z cd /home/runner/work/robotology-superbuild/robotology-superbuild/build/src/yarp-devices-forcetorque && /usr/local/bin/cmake --build .
2024-11-27T17:33:54.4278785Z [1/6] Building CXX object ftShoe/CMakeFiles/ftshoe.dir/yarp_plugin_ftshoe.cpp.o
2024-11-27T17:33:54.4279798Z [2/6] Building CXX object ftNode/CMakeFiles/ftnode.dir/yarp_plugin_ftnode.cpp.o
2024-11-27T17:33:54.4280773Z [3/6] Building CXX object ftNode/CMakeFiles/ftnode.dir/ftnodeDriver.cpp.o
2024-11-27T17:33:54.4281580Z FAILED: ftNode/CMakeFiles/ftnode.dir/ftnodeDriver.cpp.o 
2024-11-27T17:33:54.4284669Z /usr/bin/c++ -Dftnode_EXPORTS -isystem /home/runner/work/robotology-superbuild/robotology-superbuild/build/install/include -O3 -DNDEBUG -fPIC -MD -MT ftNode/CMakeFiles/ftnode.dir/ftnodeDriver.cpp.o -MF ftNode/CMakeFiles/ftnode.dir/ftnodeDriver.cpp.o.d -o ftNode/CMakeFiles/ftnode.dir/ftnodeDriver.cpp.o -c /home/runner/work/robotology-superbuild/robotology-superbuild/src/yarp-devices-forcetorque/ftNode/ftnodeDriver.cpp
2024-11-27T17:33:54.4289981Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/yarp-devices-forcetorque/ftNode/ftnodeDriver.cpp: In member function ‘virtual bool yarp::dev::ftnodeDriver::attach(yarp::dev::PolyDriver*)’:
2024-11-27T17:33:54.4293040Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/yarp-devices-forcetorque/ftNode/ftnodeDriver.cpp:320:38: error: ‘class yarp::dev::PolyDriver’ has no member named ‘getValue’
2024-11-27T17:33:54.4294946Z   320 |     pImpl->serialComPortName = poly->getValue("comport").asString();
2024-11-27T17:33:54.4296098Z       |                                      ^~~~~~~~
2024-11-27T17:33:54.4296880Z [4/6] Building CXX object ftShoe/CMakeFiles/ftshoe.dir/ftshoeDriver.cpp.o
2024-11-27T17:33:54.4297513Z ninja: build stopped: subcommand failed.
~~~

**Comment by traversaro** [comment]
CI is green!

**Pull request merged**
