### PR TITLE
Add CI for unstable branches

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/robotology-superbuild/issues/101 .

This PR is currently blocked by: 
* ~~https://github.com/robotology/robotology-superbuild/pull/275~~
* ~~https://github.com/robotology/wearables/issues/57 (@Yeshasvitvs as mantainer of the Human Dynamics profile can you ensure that this is addressed, eventually pinging @DanielePucci for obtaining resources? Thanks!)~~ Blocked by https://github.com/robotology/wearables/issues/56

### CODE REVIEW

**Comment by DanielePucci** [comment]
I think that @Yeshasvitvs may be the right person

**Comment by Yeshasvitvs** [comment]
I will address it as soon as possible within this week.

**Comment by traversaro** [comment]
Blocked by https://github.com/robotology/wearables/issues/56 .

**Comment by traversaro** [comment]
@lrapetti @Yeshasvitvs @DanielePucci As it CI testing of unstable branches is really useful, I strongly prefer to go forward on this, so for the time being I disabled the `HUMAN_DYNAMICS` component from the CI of the robotology-superbuild . However, as a release of YARP is expected at the end of this month, if https://github.com/robotology/wearables/issues/56 is not fixed by then, I will be unfortunately forced to remove all the docs for `HUMAN_DYNAMICS` from the robotology-superbuild.

**Pull request merged**
