### PR TITLE
Bump version of robotology-superbuild-dependencies-vcpkg to 0.6.0

### PR DESCRIPTION
**Pull request by traversaro**
Bump the version used in the CI.

### CODE REVIEW

**Comment by traversaro** [comment]
The compilation on Stable branches seems to be working fine, the failure are just related to https://github.com/dic-iit/bipedal-locomotion-framework .

**Comment by traversaro** [comment]
Given https://github.com/robotology/robotology-superbuild/issues/602 that will be fixed by https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/40, probably it is best to wait for 0.6.1 release.

**Comment by traversaro** [comment]
> 
> 
> Given #602 that will be fixed by [robotology/robotology-superbuild-dependencies-vcpkg#40](https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/40), probably it is best to wait for 0.6.1 release.

As @S-Dafarra noted correctly #602 is just a problem for people that do not follow the docs (a singleton set that apparently only includes me), so we can merge this to start integrating irrlicht by default.

**Comment by traversaro** [comment]
> 
> 
> The compilation on Stable branches seems to be working fine, the failure are just related to https://github.com/dic-iit/bipedal-locomotion-framework .

Those failure were fixed by https://github.com/dic-iit/bipedal-locomotion-framework/pull/172  , so please ignore them, thanks!

**Review by S-Dafarra — APPROVED** [review]

**Pull request merged**
