### PR TITLE
wb-toolbox v5

### PR DESCRIPTION
**Pull request by diegoferigo**
This PR adds the support to the new wb-toolbox v5.

@traversaro Let's wait the announcement before merging.

### CODE REVIEW

**Comment by traversaro** [comment]
https://github.com/robotology/robotology-superbuild/blob/master/cmake/template/addPathsToUserEnvVariables.ps1.in and https://github.com/robotology/robotology-superbuild/blob/master/cmake/template/removePathsFromUserEnvVariables.ps1.in need to be updated as well (this is something that needs to go in https://github.com/robotology/robotology-superbuild/issues/142).

**Comment by diegoferigo** [comment]
> powershell scripts need to be updated as well

I totally forgot we have them. Added them in the last push.

**Comment by diegoferigo** [comment]
CI failures are due jobs timeouts

**Comment by traversaro** [comment]
Yes, please ignore them.

**Comment by diegoferigo** [comment]
Announcement done, ready to merge.

**Comment by traversaro** [comment]
Merge done.

**Pull request merged**
