### PR TITLE
Release version 2022.02.2 

### PR DESCRIPTION
**Pull request by traversaro**
As discussed in https://github.com/robotology/robotology-superbuild/pull/1283#issuecomment-1268553417 , @hypothe let me know if this is ok for you.

### CODE REVIEW

**Comment by traversaro** [comment]
Please ignore the CI failures. conda-forge is a rolling release distro so an old release such as 2022.02.2 is missing fixes for the new version of the conda packages (the only meaningful CI would be something that installed the version of packages pinned to the one available in 2022.02, but we do not have that yet). Instead, the apt jobs should work, but they are currently failing due to reason external to the robotology-superbuild (see https://github.com/robotology/robotology-superbuild/issues/1285).

**Comment by traversaro** [comment]
CI is failing due to https://github.com/robotology/ycm/issues/419, that is an issue in YCM v0.13.0 that was fixed with 0.14.0 . Anyhow, as @hypothe is using it with an external YCM, I think we are good to go.

**Review by Nicogene — APPROVED** [review]

**Comment by traversaro** [comment]
@hypothe is the new release ok for you goals?

**Comment by traversaro** [comment]
Ok, great!

**Pull request merged**
