### PR TITLE
Add icub-firmware-build to icub-head profile

### PR DESCRIPTION
**Pull request by traversaro**
This PR requires that the following PRs are merged and released:
* https://github.com/robotology/ycm/pull/440
* https://github.com/robotology/icub-firmware-build/pull/124

This PR adds the `icub-firmware-build`  as a repository that is cloned and installed with the icub-head, to simplify the process of downloading the firmware corresponding to a given distro release. 

A first problem that I noticed is that while the size of firmware itself is quite limited (~4 MB for all files), the repo is quite heavy to download (~250 MB), due to the size of the whole history of icub-firmware-build binaries. To reduce the burden for existing robotology-superbuild users, for the first time for this project we pass the `GIT_SHALLOW`  option, so that a shallow clone is performed while cloning the repo (hence the modifications in https://github.com/robotology/ycm/pull/440). Unfortunately, CMake's GIT_SHALLOW is not actually shallow (see https://gitlab.kitware.com/cmake/cmake/-/issues/17770), but even if it is not a strictly shallow clone, passing `GIT_SHALLOW` the repo clone size reduced from 250 MB to 60 MB, so I think it is a worth improvement.

This PR also fixes half of https://github.com/robotology/robotology-superbuild/issues/863 .

### CODE REVIEW

**Comment by traversaro** [comment]
fyi @marcoaccame @Nicogene @S-Dafarra @GiulioRomualdi

**Comment by traversaro** [comment]
CI fails as the PRs still need to be merged.

**Review by Nicogene — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
probably we can retry to run again the CI

**Comment by traversaro** [comment]
> probably we can retry to run again the CI

We probably need to wait for icub-firmware release, or have some temporary hack.

**Comment by traversaro** [comment]
@Nicogene do you think we can have some buffer time between the icub-firmware-build release and the distro release? So we can have the time to integrate this PR.

**Comment by traversaro** [comment]
@davidetome I forgot to mention you back in time, just for your information after this PR (that we can merge once https://github.com/robotology/icub-firmware-build/pull/124 is release) the icub-firmware-build files will be present in the superbuild automatically.

**Pull request merged**
