### PR TITLE
Add the possibility to compile the casadi python bindings

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
Before merging the PR we should use casadi version `3.5.5.3`. I've just created the tag. I don't know if I can bump the new tag in this PR or handle it in a separate PR

### CODE REVIEW

**Comment by traversaro** [comment]
> 
> 
> Before merging the PR we should use casadi version `3.5.5.3`. I've just created the tag. I don't know if I can bump the new tag in this PR or handle it in a separate PR

Feel free to bump the tag in this PR.

**Comment by GiulioRomualdi** [comment]
Done in https://github.com/robotology/robotology-superbuild/pull/694/commits/6e0a26831b2cf158b90391c88768498a30a6e4df and tested on my laptop

**Comment by traversaro** [comment]
The CI is failing on a lot of configurations due to https://github.com/robotology/robotology-superbuild/issues/695 and https://github.com/robotology/robotology-superbuild/issues/693 , but some builds are hopefully passing.

**Comment by traversaro** [comment]
I bumped also latest release to test also that case.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @GiulioRomualdi @Giulero !

**Pull request merged**
