### PR TITLE
Clone all the repos in the src directory instead of external and robotology

### PR DESCRIPTION
**Pull request by traversaro**
This was discussed in https://github.com/robotology/robotology-superbuild/issues/333 . 
As this is kind an important change, it will be announced on https://github.com/robotology/QA before the PR is merged.

### CODE REVIEW

**Review by S-Dafarra — APPROVED** [review]

**Comment by traversaro** [comment]
Adding also @AlexAntn to get a feedback from a team code member.

**Review by Nicogene — APPROVED** [review]

**Comment by traversaro** [comment]
Preliminary announcement done in https://github.com/robotology/QA/discussions/451 (it seems that link done in a discussion do not result in a backlink? cc @pattacini ).

**Comment by pattacini** [comment]
>(it seems that link done in a discussion do not generate automatically a backlink as a link in other issues? cc @pattacini ).

Yep, I see. That's a downside, indeed. Hopefully, GitHub will soon fix this.
I'll check if its' already in the roadmap.

**Comment by pattacini** [comment]
Actually, it's in GH roadmap: https://github.com/github/feedback/discussions/56.

**Comment by traversaro** [comment]
@AlexAntn @vtikha Could someone from team code check if this change (discussed in https://github.com/robotology/QA/discussions/451) is ok for you or if you need to prepare some kind of migration strategy? Thanks!

**Comment by AlexAntn** [comment]
> @AlexAntn @vtikha Could someone from team code check if this change (discussed in [robotology/QA#451](https://github.com/robotology/QA/discussions/451)) is ok for you or if you need to prepare some kind of migration strategy? Thanks!

We will need to change our Dockerfiles, but the change should be quick and simple. The only problems arise from the compilation of things like gazebo plugins, but it's a matter of changing the path. Thanks for the heads-up!

**Comment by traversaro** [comment]
This change will not reach a released version before the 2021.02 release, so there should be plenty of time to adapt. However, we can also wait with this PR so that the Stable/Unstable docker builds are not broken, there is no hurry.

**Comment by traversaro** [comment]
macOS/Homebrew jobs are failing, but macOS conda-forge jobs are working fine, so probably it is an unrelated problem (tracked in https://github.com/robotology/robotology-superbuild/issues/571).

**Pull request merged**
