### PR TITLE
Update Conda documentation - add Soxr dependency

### PR DESCRIPTION
**Pull request by HosameldinMohamed**
This should fix https://github.com/robotology/robotology-superbuild/issues/1008

### CODE REVIEW

**Comment by traversaro** [comment]
Can you add the installation also in CI, see https://github.com/HosameldinMohamed/robotology-superbuild/blob/updateDocSoxr/.github/workflows/ci.yml#L80 ? Unfortunatly we still have this info duplicated.

**Comment by HosameldinMohamed** [comment]
> Can you add the installation also in CI, see https://github.com/HosameldinMohamed/robotology-superbuild/blob/updateDocSoxr/.github/workflows/ci.yml#L80 ? Unfortunatly we still have this info duplicated.

I had missed that. done in https://github.com/robotology/robotology-superbuild/pull/1087/commits/b924f2215fd9c1a65e36bd9fe75e373d5021e079

**Comment by traversaro** [comment]
Please ignore the Unstable CI failures. They are regression of https://github.com/robotology/ycm/pull/401 that will be fixed by https://github.com/robotology/icub-main/pull/787 .

**Comment by traversaro** [comment]
For consistency I would also update the apt dependencies adding `libsoxr-dev` in https://github.com/robotology/robotology-superbuild/blob/master/apt.txt (fortunatly this list is used both by docs and CI, so in this case you just need to update a single file).

**Comment by HosameldinMohamed** [comment]
> For consistency I would also update the apt dependencies adding `libsoxr-dev` in https://github.com/robotology/robotology-superbuild/blob/master/apt.txt (fortunatly this list is used both by docs and CI, so in this case you just need to update a single file).

done in https://github.com/robotology/robotology-superbuild/pull/1087/commits/f8001667ad1fd0aca317aca20f4717be306860b6

**Comment by traversaro** [comment]
Thanks @HosameldinMohamed !

**Pull request merged**
