### PR TITLE
Add ROBOTOLOGY_ENABLE_IHMC profile

### PR DESCRIPTION
**Pull request by fiorisi**
This pull request includes the logic to add the package ihmc-ors-yarp. 
In particular, it has been created a new profile named `ROBOTOLOGY_ENABLE_IHMC` and has been updated the documentation.

### CODE REVIEW

**Comment by traversaro** [comment]
Hi @fiorisi , I cleaned up the installation instructions to document also how to install the necessary system dependencies (such as Asio) also on Windows and macOS (I also cleaned up the documentation of other options for consistency). Let me know if this is ok for you.

**Comment by traversaro** [comment]
I also made the option **not** advanced, as it is a fully supported and documented option.

**Comment by traversaro** [comment]
I also added the testing of the compilation to Travis, especially because we are currently using the `master` branch of fastcdr for compilation (so the compilation could fail out of nowhere if there are problems there!).

**Comment by traversaro** [comment]
Added @gabrielenava as mantainer of the IHMC profile, @fiorisi waiting on your approval (just comment) to merge.

**Comment by fiorisi** [comment]
Thanks @traversaro.

**Pull request merged**
