### PR TITLE
Fix macOS Travis build

### PR DESCRIPTION
**Pull request by lrapetti**
As discussed in https://github.com/lrapetti/robotology-superbuild/pull/4.
Fix https://github.com/robotology/robotology-superbuild/issues/141, and closes https://github.com/robotology/robotology-superbuild/pull/149

### CODE REVIEW

**Comment by traversaro** [comment]
A lot of test failed, but that is probably due to something else.

**Comment by traversaro** [comment]
There is a new macOS error, see https://travis-ci.org/robotology/robotology-superbuild/jobs/470411651 .

**Comment by traversaro** [comment]
Hopefully https://github.com/robotology/robotology-superbuild/pull/153/commits/0df2f777a9a67738954dd3519a3ecbf2ad1e7ae1 should fix it finally.

**Comment by lrapetti** [comment]
> There is a new macOS error, see https://travis-ci.org/robotology/robotology-superbuild/jobs/470411651 .

My bad, I forgot to remove that workaround in this PR,
it seems it was no longer necessary (https://changelog.travis-ci.com/oclint-is-removed-from-mac-builds-79270).
Now everything should be fixed.

**Comment by diegoferigo** [comment]
@lrapetti @traversaro For the record, I just discovered that if the `before_install` step is missing, the addon for homebrew does not work. Probably in your case it didn't work due to this reason, I opened [a bug upstream](https://travis-ci.community/t/homebrew-addon-does-not-work-if-before-install-step-is-missing/1564).

**Pull request merged**
