### PR TITLE
Add YCM publications to README.md

### PR DESCRIPTION
**Pull request by drdanz**

### CODE REVIEW

**Comment by traversaro** [comment]
Can we put the DOI link as a normal text link instead of an image? A normal text simplifies the copy&pasting of the DOI, quite convenient if you manage your publications  using a program such as Zenodo or Mendeley.

**Comment by drdanz** [comment]
Sure, do you prefer just the doi or or the doi url? (i.e. `DOI 10.1109/IRC.2018.00014` or `https://doi.org/10.1109/IRC.2018.00014`)

**Comment by traversaro** [comment]
Both are ok, given that it is an URL probably the DOI URL makes more sense.

**Comment by traversaro** [comment]
Thanks!

**Pull request merged**
