### PR TITLE
Modify install-miniforge to fully support zsh

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by traversaro** [comment]
Please ignore CI failures, they will be fixed by https://github.com/robotology/robotology-superbuild/pull/840 and are unrelated.

**Comment by traversaro** [comment]
Friendly ping @lrapetti @Giulero, if you are unable for lack of time to review the PR feel free to let me know.  : )

**Comment by Giulero** [comment]
Sorry @traversaro! Looks good! I also followed the instructions and everything went well.
Thanks!

**Review by Giulero — APPROVED** [review]

**Review by lrapetti — APPROVED** [review]
Sorry for the delay, I had a look at the PR, and also tried to run the `conda init zsh` and the `.zshrc` seems to be updated correctly on `MacOS`

**Comment by traversaro** [comment]
By the way, I had to manually mention `conda init zsh`  in the README due to https://github.com/conda-forge/miniforge/issues/127 .

**Pull request merged**
