### PR TITLE
Use YARP master branch in Unstable tags

### PR DESCRIPTION
**Pull request by traversaro**
Revert https://github.com/robotology/robotology-superbuild/pull/961 as the issue was solved by https://github.com/robotology/gazebo-yarp-plugins/pull/599 .

### CODE REVIEW

**Comment by traversaro** [comment]
Unstable is now failing, but for another reason:
~~~
2021-12-22T16:04:29.7621615Z -- Build files have been written to: /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things
2021-12-22T16:04:37.1402008Z [235/248] Performing build step for 'funny-things'
2021-12-22T16:04:37.1403659Z FAILED: src/funny-things/CMakeFiles/YCMStamp/funny-things-build /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/CMakeFiles/YCMStamp/funny-things-build 
2021-12-22T16:04:37.1406115Z cd /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things && /usr/bin/cmake --build . && /usr/bin/cmake -E touch /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/CMakeFiles/YCMStamp/funny-things-build
2021-12-22T16:04:37.1407593Z [1/10] Generating code from iCubBlinker.thrift
2021-12-22T16:04:37.1408531Z [2/10] Building CXX object modules/iCubBreather/CMakeFiles/iCubBreather.dir/iCubBreatherModule.cpp.o
2021-12-22T16:04:37.1409786Z [3/10] Building CXX object modules/iCubBreather/CMakeFiles/iCubBreather.dir/iCubBreatherThread.cpp.o
2021-12-22T16:04:37.1410864Z [4/10] Building CXX object modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/main.cpp.o
2021-12-22T16:04:37.1411610Z [5/10] Linking CXX executable bin/iCubBreather
2021-12-22T16:04:37.1412181Z [6/10] Running utility command for copy_lua_in_build
2021-12-22T16:04:37.1412965Z [7/10] Building CXX object modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/iCubBlinker_IDL.cpp.o
2021-12-22T16:04:37.1413921Z FAILED: modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/iCubBlinker_IDL.cpp.o 
2021-12-22T16:04:37.1417364Z /usr/bin/c++  -I/__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/modules/iCubBlinker -isystem /__w/robotology-superbuild/robotology-superbuild/build/install/include -g -std=c++1z -MD -MT modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/iCubBlinker_IDL.cpp.o -MF modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/iCubBlinker_IDL.cpp.o.d -o modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/iCubBlinker_IDL.cpp.o -c /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/modules/iCubBlinker/iCubBlinker_IDL.cpp
2021-12-22T16:04:37.1420920Z /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/modules/iCubBlinker/iCubBlinker_IDL.cpp:17:11: error: "'blink_fast' will never be called, since 'blink' starts with the same tag"
2021-12-22T16:04:37.1422404Z  YARP_COMPILER_ERROR("'blink_fast' will never be called, since 'blink' starts with the same tag")
2021-12-22T16:04:37.1423012Z            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-12-22T16:04:37.1424418Z /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/modules/iCubBlinker/iCubBlinker_IDL.cpp:18:11: error: "'blink_naturalistic' will never be called, since 'blink' starts with the same tag"
2021-12-22T16:04:37.1425976Z  YARP_COMPILER_ERROR("'blink_naturalistic' will never be called, since 'blink' starts with the same tag")
2021-12-22T16:04:37.1426627Z            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-12-22T16:04:37.1427333Z [8/10] Building CXX object modules/funnyPostures/CMakeFiles/funnyPostures.dir/main.cpp.o
2021-12-22T16:04:37.1428109Z ninja: build stopped: subcommand failed.
~~~

Probably this is related to https://github.com/robotology/yarp/pull/2780 .

**Review by Nicogene — APPROVED** [review]

**Comment by traversaro** [comment]
Now CI should be happy after https://github.com/robotology/funny-things/issues/22 .

**Comment by traversaro** [comment]
The only failure can be ignored has it is related to https://github.com/robotology/robotology-superbuild/issues/974 .

**Comment by traversaro** [comment]
> Now CI should be happy after [robotology/funny-things#22](https://github.com/robotology/funny-things/issues/22) .

Obviously, not. The error is now:
~~~
2021-12-24T13:10:43.9642369Z [24/37] Building CXX object devices/wholeBodyDynamics/CMakeFiles/wholeBodyDynamicsDevice.dir/WholeBodyDynamicsDevice.cpp.o
2021-12-24T13:10:43.9644045Z FAILED: devices/wholeBodyDynamics/CMakeFiles/wholeBodyDynamicsDevice.dir/WholeBodyDynamicsDevice.cpp.o 
2021-12-24T13:10:43.9652156Z /usr/bin/c++ -D_USE_MATH_DEFINES -DwholeBodyDynamicsDevice_EXPORTS -I/__w/robotology-superbuild/robotology-superbuild/src/whole-body-estimators/devices/wholeBodyDynamics -I/__w/robotology-superbuild/robotology-superbuild/build/src/whole-body-estimators/idl/wholeBodyDynamicsSettings/autogenerated/include -I/__w/robotology-superbuild/robotology-superbuild/build/src/whole-body-estimators/idl/wholeBodyDynamics_IDLServer/autogenerated/include -I/__w/robotology-superbuild/robotology-superbuild/src/whole-body-estimators/libraries/ctrlLibRT/include -isystem /usr/include/eigen3 -isystem /__w/robotology-superbuild/robotology-superbuild/build/install/include -g -fPIC -std=gnu++1z -MD -MT devices/wholeBodyDynamics/CMakeFiles/wholeBodyDynamicsDevice.dir/WholeBodyDynamicsDevice.cpp.o -MF devices/wholeBodyDynamics/CMakeFiles/wholeBodyDynamicsDevice.dir/WholeBodyDynamicsDevice.cpp.o.d -o devices/wholeBodyDynamics/CMakeFiles/wholeBodyDynamicsDevice.dir/WholeBodyDynamicsDevice.cpp.o -c /__w/robotology-superbuild/robotology-superbuild/src/whole-body-estimators/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp
2021-12-24T13:10:43.9659590Z In file included from /__w/robotology-superbuild/robotology-superbuild/src/whole-body-estimators/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp:2:0:
2021-12-24T13:10:43.9662079Z /__w/robotology-superbuild/robotology-superbuild/src/whole-body-estimators/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.h:245:32: error: 'Editor' in 'class wholeBodyDynamicsSettings' does not name a type
2021-12-24T13:10:43.9663746Z      wholeBodyDynamicsSettings::Editor settingsEditor;
2021-12-24T13:10:43.9664339Z                                 ^~~~~~
2021-12-24T13:10:43.9666373Z /__w/robotology-superbuild/robotology-superbuild/src/whole-body-estimators/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp: In constructor 'yarp::dev::WholeBodyDynamicsDevice::WholeBodyDynamicsDevice()':
2021-12-24T13:10:43.9669567Z /__w/robotology-superbuild/robotology-superbuild/src/whole-body-estimators/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp:40:53: error: class 'yarp::dev::WholeBodyDynamicsDevice' does not have any field named 'settingsEditor'
2021-12-24T13:10:43.9671169Z                                                      settingsEditor(settings)
2021-12-24T13:10:43.9671636Z                                                      ^~~~~~~~~~~~~~
2021-12-24T13:10:43.9673639Z /__w/robotology-superbuild/robotology-superbuild/src/whole-body-estimators/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp: In member function 'bool yarp::dev::WholeBodyDynamicsDevice::openSettingsPort()':
2021-12-24T13:10:43.9676297Z /__w/robotology-superbuild/robotology-superbuild/src/whole-body-estimators/devices/wholeBodyDynamics/WholeBodyDynamicsDevice.cpp:65:28: error: 'settingsEditor' was not declared in this scope
2021-12-24T13:10:43.9677767Z      settingsPort.setReader(settingsEditor);
2021-12-24T13:10:43.9678311Z                             ^~~~~~~~~~~~~~
~~~

**Comment by traversaro** [comment]
A fix is provided in https://github.com/robotology/whole-body-estimators/pull/135 . To test it, we temporarly use the `fix_yarp36` branch of whole-body-estimators.

**Comment by traversaro** [comment]
> A fix is provided in [robotology/whole-body-estimators#135](https://github.com/robotology/whole-body-estimators/pull/135) . To test it, we temporarly use the `fix_yarp36` branch of whole-body-estimators.

That fix is working, but there is a new compilation failure caused by YARP 3.6:
~~~
2021-12-24T13:58:14.0840628Z [12/181] Building CXX object src/YarpUtilities/CMakeFiles/VectorsCollection.dir/autogenerated/src/VectorsCollection.cpp.o
2021-12-24T13:58:14.0842059Z FAILED: src/YarpUtilities/CMakeFiles/VectorsCollection.dir/autogenerated/src/VectorsCollection.cpp.o 
2021-12-24T13:58:14.0849257Z /usr/share/miniconda3/envs/test/bin/x86_64-conda-linux-gnu-c++ -DUSING_DEPRECATED_UPPERCASE_YARP_OS_TARGET -DVectorsCollection_EXPORTS -I/home/runner/work/robotology-superbuild/robotology-superbuild/build/src/bipedal-locomotion-framework/src/YarpUtilities/autogenerated/include -isystem /home/runner/work/robotology-superbuild/robotology-superbuild/build/install/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /usr/share/miniconda3/envs/test/include -O3 -DNDEBUG -fPIC -MD -MT src/YarpUtilities/CMakeFiles/VectorsCollection.dir/autogenerated/src/VectorsCollection.cpp.o -MF src/YarpUtilities/CMakeFiles/VectorsCollection.dir/autogenerated/src/VectorsCollection.cpp.o.d -o src/YarpUtilities/CMakeFiles/VectorsCollection.dir/autogenerated/src/VectorsCollection.cpp.o -c /home/runner/work/robotology-superbuild/robotology-superbuild/build/src/bipedal-locomotion-framework/src/YarpUtilities/autogenerated/src/VectorsCollection.cpp
2021-12-24T13:58:14.0856864Z /home/runner/work/robotology-superbuild/robotology-superbuild/build/src/bipedal-locomotion-framework/src/YarpUtilities/autogenerated/src/VectorsCollection.cpp: In member function 'bool BipedalLocomotion::YarpUtilities::VectorsCollection::read_vectors(yarp::os::idl::WireReader&)':
2021-12-24T13:58:14.0860258Z /home/runner/work/robotology-superbuild/robotology-superbuild/build/src/bipedal-locomotion-framework/src/YarpUtilities/autogenerated/src/VectorsCollection.cpp:99:18: error: redeclaration of 'uint32_t _size'
2021-12-24T13:58:14.0861621Z    99 |         uint32_t _size;
2021-12-24T13:58:14.0861961Z       |                  ^~~~~
2021-12-24T13:58:14.0863595Z /home/runner/work/robotology-superbuild/robotology-superbuild/build/src/bipedal-locomotion-framework/src/YarpUtilities/autogenerated/src/VectorsCollection.cpp:81:18: note: 'uint32_t _size' previously declared here
2021-12-24T13:58:14.0864976Z    81 |         uint32_t _size;
2021-12-24T13:58:14.0865311Z       |                  ^~~~~
2021-12-24T13:58:14.0867629Z /home/runner/work/robotology-superbuild/robotology-superbuild/build/src/bipedal-locomotion-framework/src/YarpUtilities/autogenerated/src/VectorsCollection.cpp: In member function 'bool BipedalLocomotion::YarpUtilities::VectorsCollection::nested_read_vectors(yarp::os::idl::WireReader&)':
2021-12-24T13:58:14.0870621Z /home/runner/work/robotology-superbuild/robotology-superbuild/build/src/bipedal-locomotion-framework/src/YarpUtilities/autogenerated/src/VectorsCollection.cpp:185:18: error: redeclaration of 'uint32_t _size'
2021-12-24T13:58:14.0871966Z   185 |         uint32_t _size;
2021-12-24T13:58:14.0872317Z       |                  ^~~~~
2021-12-24T13:58:14.0873952Z /home/runner/work/robotology-superbuild/robotology-superbuild/build/src/bipedal-locomotion-framework/src/YarpUtilities/autogenerated/src/VectorsCollection.cpp:167:18: note: 'uint32_t _size' previously declared here
2021-12-24T13:58:14.0875317Z   167 |         uint32_t _size;
2021-12-24T13:58:14.0875664Z       |                  ^~~~~
~~~

**Comment by traversaro** [comment]
> > A fix is provided in [robotology/whole-body-estimators#135](https://github.com/robotology/whole-body-estimators/pull/135) . To test it, we temporarly use the `fix_yarp36` branch of whole-body-estimators.
> 
> That fix is working, but there is a new compilation failure caused by YARP 3.6:

I opened an issue (https://github.com/robotology/yarp/issues/2787) and a PR with a failing test (https://github.com/robotology/yarp/pull/2786) related to this.

**Comment by traversaro** [comment]
> > > A fix is provided in [robotology/whole-body-estimators#135](https://github.com/robotology/whole-body-estimators/pull/135) . To test it, we temporarly use the `fix_yarp36` branch of whole-body-estimators.
> > 
> > 
> > That fix is working, but there is a new compilation failure caused by YARP 3.6:
> 
> I opened an issue ([robotology/yarp#2787](https://github.com/robotology/yarp/issues/2787)) and a PR with a failing test ([robotology/yarp#2786](https://github.com/robotology/yarp/pull/2786)) related to this.

This was fixed by https://github.com/robotology/yarp/pull/2790, thanks @drdanz !

**Comment by traversaro** [comment]
Compilation succeded!

**Comment by traversaro** [comment]
Due to YARP 3.6 release, now we need to merge this to fix the Unstable CI.

**Review by Nicogene — APPROVED** [review]

**Comment by traversaro** [comment]
> Compilation succeded, we just need to merge [robotology/whole-body-estimators#135](https://github.com/robotology/whole-body-estimators/pull/135) to proceed.

I just merged it, I will now remove the workaround of using the PR branch.

**Comment by traversaro** [comment]
CI is happy! Merging.

**Pull request merged**
