### PR TITLE
Enable compilation of Human Dynamics component in Continuous Integration

### PR DESCRIPTION
**Pull request by traversaro**
Thanks to https://github.com/robotology/wearables/pull/65 , the issue with wearables compilation against the unstable branch of YARP was fixed.

### CODE REVIEW

**Comment by traversaro** [comment]
Everything works fine on both Windows and Linux. : ) 
@lrapetti @Yeshasvitvs

**Comment by traversaro** [comment]
And.. obviously everything compiles on Windows because there is an undocumented if that disables `human-dynamics-estimation` on Windows, see https://github.com/robotology/robotology-superbuild/pull/231/files#r349535694 .  :D

**Comment by traversaro** [comment]
> And.. obviously everything compiles on Windows because there is an undocumented if that disables `human-dynamics-estimation` on Windows, see https://github.com/robotology/robotology-superbuild/pull/231/files#r349535694 . :D

I could not find any reason for which `human-dynamics-estimation` was not enabled on Windows in the original PR https://github.com/robotology/robotology-superbuild/pull/231 . @kouroshD do you remember anything related to this?

**Comment by traversaro** [comment]
Merge currently blocked by https://github.com/robotology/human-dynamics-estimation/issues/160 .

**Comment by traversaro** [comment]
Everything works fine now, thanks @lrapetti @diegoferigo !

**Comment by kouroshD** [comment]
> > And.. obviously everything compiles on Windows because there is an undocumented if that disables `human-dynamics-estimation` on Windows, see https://github.com/robotology/robotology-superbuild/pull/231/files#r349535694 . :D
> 
> I could not find any reason for which `human-dynamics-estimation` was not enabled on Windows in the original PR #231 . @kouroshD do you remember anything related to this?

I cannot recall now, but probably because there were some problem to run/build it on Windows when that PR was open. In any case, the right way is to have it in Windows as well.
In any case, we do not have visualization in Windows if I am not wrong, and normally we need to visualize, which needs to install ros in Windows.

**Pull request merged**
