### PR TITLE
Add support for Visual Studio 2022 in CI and Documentation

### PR DESCRIPTION
**Pull request by traversaro**
To avoid duplicate the number of jobs, on Windows we compile against Visual Studio 2022 for Stable branches, and against Visual Studio 2019 for Unstable branches.

### CODE REVIEW

**Review by isorrentino — APPROVED** [review]

**Comment by traversaro** [comment]
Unfortunatly the `windows-2019` only has VS2019, while `windows-2022` has only VS2022. Either we use the platform, or we build for both `windows-2022` and `windows-2019` .

**Comment by traversaro** [comment]
Visual Studio 2022 builds in CI are failing as they are not able to find OpenCV:
~~~
2022-01-11T11:47:17.4005895Z   CMake Warning at C:/Miniconda3/envs/test/Library/CMake/OpenCVConfig.cmake:176 (message):
2022-01-11T11:47:17.4008038Z     Found OpenCV Windows Pack but it has no binaries compatible with your
2022-01-11T11:47:17.4009289Z     configuration.
2022-01-11T11:47:17.4009945Z   
2022-01-11T11:47:17.4010725Z     You should manually point CMake variable OpenCV_DIR to your build of OpenCV
2022-01-11T11:47:17.4011486Z     library.
2022-01-11T11:47:17.4012084Z   Call Stack (most recent call first):
2022-01-11T11:47:17.4012789Z     CMakeLists.txt:39 (find_package)
2022-01-11T11:47:17.4013375Z   
2022-01-11T11:47:17.4013790Z   
2022-01-11T11:47:17.4014594Z   CMake Error at CMakeLists.txt:39 (find_package):
2022-01-11T11:47:17.4015389Z     Found package configuration file:
2022-01-11T11:47:17.4015960Z   
2022-01-11T11:47:17.4016688Z       C:/Miniconda3/envs/test/Library/CMake/OpenCVConfig.cmake
2022-01-11T11:47:17.4017399Z   
2022-01-11T11:47:17.4018182Z     but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
2022-01-11T11:47:17.4018942Z     NOT FOUND.
2022-01-11T11:47:17.4019398Z   
2022-01-11T11:47:17.4019836Z   
2022-01-11T11:47:17.4020635Z   -- Configuring incomplete, errors occurred!
~~~

Visual Studio 2022 builds should be able to use Visual Studio 2019 binaries with no problems (see https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170), but for some reason the OpenCVConfig.cmake file seems to think otherwise.

**Comment by traversaro** [comment]
> Visual Studio 2022 builds should be able to use Visual Studio 2019 binaries with no problems (see https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170), but for some reason the OpenCVConfig.cmake file seems to think otherwise.

The `OpenCVConfig.cmake` file has some custom logic that was not updated to handle VS2022 in 4.5.3 . The modification to support VS2022 with binaries built with earlier versions of VS can be found in https://github.com/opencv/opencv/pull/20831 .

**Comment by traversaro** [comment]
> The first tagged version with that modification is 4.5.4 .

We need to either bump the version of opencv in conda-forge, or backport the fix.

**Comment by traversaro** [comment]
> > The first tagged version with that modification is 4.5.4 .
> 
> We need to either bump the version of opencv in conda-forge, or backport the fix.

Hopefully this will be fixed by https://github.com/conda-forge/opencv-feedstock/pull/296 .

**Comment by traversaro** [comment]
The OpenCV issue with Visual Studio 2022 should be finally solved thanks to:
* https://github.com/conda-forge/opencv-feedstock/pull/296
* https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2392

**Pull request merged**
