### PR TITLE
Add compilation of ROBOTOLOGY_USES_GAZEBO in Travis

### PR DESCRIPTION
**Pull request by traversaro**
Finally working on both macOS and Linux. : ) 
Fix https://github.com/robotology/robotology-superbuild/issues/52 .
 : )

### CODE REVIEW

**Comment by traversaro** [comment]
Still too close to the 48-minutes limit, the net effect is that the test is flaky. Let's try to reduce of at least a minute the test, and then we eventually work to a more permanent solution (for example it seems to be that ccache si not properly working, and that will reduce the build time considerably).

**Comment by diegoferigo** [comment]
@traversaro I did many attempts to use ccache in osx when using the Xcode generator but I never managed to make it work. If you use instead Unix Makefile it works.

**Comment by traversaro** [comment]
> I did many attempts to use ccache in osx when using the Xcode generator but I never managed to make it work. If you use instead Unix Makefile it works. 

Cool, I missed this info.

**Comment by traversaro** [comment]
The `brew upgrade` seems not to be strictly necessary, so I removed it for now. This saves ~4 minutes, that should be enough margin for now.

**Pull request merged**
