### PR TITLE
Add yarp-device-keyboard-joypad when compiling ROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS

### PR DESCRIPTION
**Pull request by traversaro**
At the moment, we use the vendored imgui. Once we have more then a project using imgui, we can look into installing it via apt and/or conda.

The PR just needs a release to be merged, see https://github.com/ami-iit/yarp-device-keyboard-joypad/issues/4 .

### CODE REVIEW

**Comment by S-Dafarra** [comment]
On ``mac``, which I was not testing in CI, there is this error
```
[6/13] Building CXX object src/devices/keyboard-joypad/CMakeFiles/yarp_keyboard-joypad.dir/KeyboardJoypad.cpp.o
FAILED: src/devices/keyboard-joypad/CMakeFiles/yarp_keyboard-joypad.dir/KeyboardJoypad.cpp.o 
/Users/runner/miniconda3/envs/test/bin/arm64-apple-darwin20.0.0-clang++ -Dyarp_keyboard_joypad_EXPORTS -I/Users/runner/work/robotology-superbuild/robotology-superbuild/src/yarp-device-keyboard-joypad/src/devices/keyboard-joypad -I/Users/runner/work/robotology-superbuild/robotology-superbuild/b/src/yarp-device-keyboard-joypad/_deps/imgui-src/backends -I/Users/runner/work/robotology-superbuild/robotology-superbuild/b/src/yarp-device-keyboard-joypad/_deps/imgui-src -isystem /Users/runner/work/robotology-superbuild/robotology-superbuild/b/install/include -iframework /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/runner/miniconda3/envs/test/include -O3 -DNDEBUG -std=c++20 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -fPIC -MD -MT src/devices/keyboard-joypad/CMakeFiles/yarp_keyboard-joypad.dir/KeyboardJoypad.cpp.o -MF src/devices/keyboard-joypad/CMakeFiles/yarp_keyboard-joypad.dir/KeyboardJoypad.cpp.o.d -o src/devices/keyboard-joypad/CMakeFiles/yarp_keyboard-joypad.dir/KeyboardJoypad.cpp.o -c /Users/runner/work/robotology-superbuild/robotology-superbuild/src/yarp-device-keyboard-joypad/src/devices/keyboard-joypad/KeyboardJoypad.cpp
/Users/runner/work/robotology-superbuild/robotology-superbuild/src/yarp-device-keyboard-joypad/src/devices/keyboard-joypad/KeyboardJoypad.cpp:14:10: fatal error: 'GL/gl.h' file not found
#include <GL/gl.h>
         ^~~~~~~~~
1 error generated.
```

**Comment by traversaro** [comment]
That is strange. It is a error related to OpenGL, but on Linux that happens because some CDT packages are missing, but I never saw that error on macOS. I guess it can be related to the recent upgrade of `macos-latest` that now points to `macos-14`, that is Apple Silicon (i.e. arm64) processors.

**Comment by traversaro** [comment]
> That is strange. It is a error related to OpenGL, but on Linux that happens because some CDT packages are missing, but I never saw that error on macOS. I guess it can be related to the recent upgrade of `macos-latest` that now points to `macos-14`, that is Apple Silicon (i.e. arm64) processors.

Actually this is not possible, as we are still using `macos-12` in those jobs.

**Comment by S-Dafarra** [comment]
Also, I am using similar includes in https://github.com/ami-iit/yarp-device-openxrheadset

**Comment by traversaro** [comment]
> Also, I am using similar includes in https://github.com/ami-iit/yarp-device-openxrheadset

OpenXR conda package is not available on macOS (see https://github.com/conda-forge/openxr-sdk-feedstock), so I guess we never tested it there. Anyhow, we can also skip the repo on macos, let me check.

**Comment by S-Dafarra** [comment]
It seems that the ``gl.h`` file is in a different path in ``macos``: https://stackoverflow.com/a/26745337

**Comment by traversaro** [comment]
> It seems that the `gl.h` file is in a different path in `macos`: https://stackoverflow.com/a/26745337

Ah, there are a few example of this in robotology apparently: https://github.com/search?q=org%3Arobotology+OpenGL%2Fgl.h&type=code .

**Comment by traversaro** [comment]
Add release to latest.releases. If the CI is happy, let's merge.

**Pull request merged**
