### PR TITLE
Move YARP_TAG of ProjectsTagsStable to yarp-3.5

### PR DESCRIPTION
**Pull request by traversaro**
This means that users that use the `Stable` setting of the robotology-superbuild (that is the default) will start getting the new yarp 3.5 instead of yarp 3.4 . This may be reveal new problems as several changes are present, so please report any new issue.

### CODE REVIEW

**Comment by traversaro** [comment]
@robotology/iit-dynamic-interaction-control This PR will change the default branch of yarp used to 3.5. If there are some upcoming demos for which you want a stable solution, you may want to stick to 2021.08 release for the time being.

**Review by pattacini — APPROVED** [review]

**Review by Nicogene — APPROVED** [review]

**Comment by traversaro** [comment]
@drdanz suggested to wait for https://github.com/robotology/yarp/pull/2699 to land on yarp-3.5 branch.

**Comment by traversaro** [comment]
We also need to coordinate the merge of devel of https://github.com/robotology/gazebo-yarp-plugins in master, as the master (i.e. 3.6.2 release) is not compatible with YARP 3.5.

**Comment by traversaro** [comment]
> 
> 
> @drdanz suggested to wait for [robotology/yarp#2699](https://github.com/robotology/yarp/pull/2699) to land on yarp-3.5 branch.

Merged!

**Comment by traversaro** [comment]
> 
> 
> We also need to coordinate the merge of devel of https://github.com/robotology/gazebo-yarp-plugins in master, as the master (i.e. 3.6.2 release) is not compatible with YARP 3.5.

For the time being, I switched stable to use `devel` of gyp. After this is merged, I will merge https://github.com/robotology/gazebo-yarp-plugins/pull/573, and remove the workaround (and do a release of gyp so that we can update latestreleases as well).

**Review by pattacini — APPROVED** [review]

**Comment by Nicogene** [comment]
Maybe before merging this we should await to do the 2021.08.feat-01 release ?

**Comment by traversaro** [comment]
> 
> 
> Maybe before merging this we should await to do the 2021.08.feat-01 release ?

I think the `2021.08.feat-01` can be tagged on the `releases/2021.08`  branch, what do you think?

**Review by pattacini — APPROVED** [review]

**Comment by Nicogene** [comment]
> I think the 2021.08.feat-01 can be tagged on the releases/2021.08 branch, what do you think?

For me is fine, but I need that https://github.com/robotology/robotology-superbuild/commit/29fdc5df5bdcc45355883f58d05a0c31d65891d9 is cherry-picked before tagging

**Comment by traversaro** [comment]
> 
> 
> > I think the 2021.08.feat-01 can be tagged on the releases/2021.08 branch, what do you think?
> 
> For me is fine, but I need that [29fdc5d](https://github.com/robotology/robotology-superbuild/commit/29fdc5df5bdcc45355883f58d05a0c31d65891d9) is cherry-picked before tagging

Yep, we can backport any change we like to that branch.

**Pull request merged**
