### PR TITLE
Update osqp to v0.6.0

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/robotology-superbuild/issues/242 .

### CODE REVIEW

**Comment by traversaro** [comment]
@GiulioRomualdi apparently OsqpEigen `devel` is not compatible with osqp 0.6.0 .  Do you think it  make then sense to use `master` as the target branch for both "Stable" and  "Unstable" builds.

**Comment by GiulioRomualdi** [comment]
> @GiulioRomualdi apparently OsqpEigen `devel` is not compatible with osqp 0.6.0 . Do you think it make then sense to use `master` as the target branch for both "Stable" and "Unstable" builds?

That's really strange, `devel` is on top of `master`

**Comment by GiulioRomualdi** [comment]
CI is failing because of https://github.com/robotology/osqp-eigen/blob/master/CMakeLists.txt#L105

Similar to: https://github.com/robotology/idyntree/pull/629

**Comment by traversaro** [comment]
> 
> 
> CI is failing because of https://github.com/robotology/osqp-eigen/blob/master/CMakeLists.txt#L105
> 
> Similar to: [robotology/idyntree#629](https://github.com/robotology/idyntree/pull/629)

Yes, sorry I overlooked the error message. How do you prefer to proceed? In general it may be expected that not all the unstable branches of all the project of the robotology-superbuild, are compatible with one another, so in the "Unstable" branches we actually just collect an arbitrary compatible set of branches, but there is no strict requirement to have the unstable branches of all dependencies. If you prefer we can just use the `master` branch of `osqp-eigen` with the `devel` branch of `walking-controllers` .

**Comment by GiulioRomualdi** [comment]
https://github.com/robotology/osqp-eigen/pull/42 should fix the problem

**Comment by GiulioRomualdi** [comment]
`SameMinorVersion` was a terrible workaround to https://github.com/oxfordcontrol/osqp/issues/195.
`osqp-eigen v0.5.1` is back-compatible with `v0.4.1` so there shouldn't be any problems

**Comment by traversaro** [comment]
Thanks @GiulioRomualdi . I would wait for next week to merge this, to hear if someone needs to stick to osqp 0.5 .

**Pull request merged**
