### PR TITLE
Fix support for zsh in conda binary activation scripts

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/robotology-superbuild/issues/779 . This PR should fix all the `pathappend:3: bad substitution` experienced by zsh users such as @lrapetti or @Giulero .

We temporary install `multisheller` from a fixed commit to include the required fix https://github.com/mamba-org/multisheller/pull/13 .

### CODE REVIEW

**Comment by traversaro** [comment]
Please ignore the CI failures, there are usual network non-reproducible issues. The relevant CI job is https://github.com/robotology/robotology-superbuild/actions/runs/982744267, and that was able to produce conda packages.

**Comment by traversaro** [comment]
Friendly ping @lrapetti @Giulero @nunoguedelha (I tagged you as zsh users), as usual there is no need to understand everything in depth in the PR, just checking if it make sense is probably enough.

**Review by lrapetti — APPROVED** [review]
Thanks @traversaro, sorry but I was AFK last week.
The idea overall seems ok, even if am not aware of some details.

**Comment by nunoguedelha** [comment]
Sorry @traversaro , I haven't tried at all yet using `zsh` shell.

**Pull request merged**
