### PR TITLE
Migrate YARP_telemetry to robometry

### PR DESCRIPTION
**Pull request by Nicogene**
This PR introduce all the changes for using the renamed YARP_telemetry (`robometry`).

I am afraid this PR's CI will fail until the repos that uses `robometry` do not do the migration.

### CODE REVIEW

**Comment by traversaro** [comment]
I guess the PR is not failing just because blf and wearables are automatically disabling the part that depend on yarp-telemetry. Probably it make sense to just wait for them to switch to robometry. Alternative, a possible good idea is to just install robometry and yarp-telemetry side-by-side until they have been upgraded?

cc @S-Dafarra @lrapetti @GiulioRomualdi

**Comment by S-Dafarra** [comment]
I would vote for switching first

**Comment by GiulioRomualdi** [comment]
Regarding blf I can open a PR before the end of the day switching from yarp-telemetry to robometry

**Comment by traversaro** [comment]
> However to fully run the conda ci in blf we need robometry in conda. Shall we port it from robotology channer to condaforge?

The tricky part for now is that robometry still has a YARP part (the device), and YARP still is not in conda-forge ( https://github.com/conda-forge/staged-recipes/pull/18234 ). An option is to split the device in a robometry-yarp repo, but I do not know what where the plan of @Nicogene on this.

**Comment by lrapetti** [comment]
If needed I can also change from `YARP-telemetry` to `robometry` in wearables, but is there plan to release a tag for `robometry`? Because generally, in `wearables`, we test the CI against a stable tag of the dependencies (see https://github.com/robotology/wearables/blob/adf2f6d995835f6d111ca7122ac5fed81f8fd1f8/.github/workflows/ci.yml#L21)

**Comment by Nicogene** [comment]
> > However to fully run the conda ci in blf we need robometry in conda. Shall we port it from robotology channer to condaforge?
> 
> The tricky part for now is that robometry still has a YARP part (the device), and YARP still is not in conda-forge ( [conda-forge/staged-recipes#18234](https://github.com/conda-forge/staged-recipes/pull/18234) ). An option is to split the device in a robometry-yarp repo, but I do not know what where the plan of @Nicogene on this.

We spoke more in general about the thing to move the yarp-devices to a separate repository but it is something we have not planned at least in the near future.
Maybe having a single repo for just the `telemetryDeviceDumper` is too much ?

**Comment by Nicogene** [comment]
> If needed I can also change from `YARP-telemetry` to `robometry` in wearables, but is there plan to release a tag for `robometry`? Because generally, in `wearables`, we test the CI against a stable tag of the dependencies (see https://github.com/robotology/wearables/blob/adf2f6d995835f6d111ca7122ac5fed81f8fd1f8/.github/workflows/ci.yml#L21)

The last `YARP_telemetry` tag is `v0.5.1`, as soon as we see that this refactoring didn't give any problem we will tag it as `v1.0.0`

**Comment by traversaro** [comment]
> I am afraid this PR's CI will fail until the repos that uses `robometry` do not do the migration.

Fortunatly, this is not the case as the downstream projects will just not compile telemetry-related elements if `YARP_telemetry/robometry` is found.

**Comment by traversaro** [comment]
> Maybe having a single repo for just the `telemetryDeviceDumper` is too much ?

As you prefer, if you want to stress that `robometry` is YARP-indipendent it is useful to avoid having YARP-related parts in it. However, this is not strictly related to this PR.

**Comment by traversaro** [comment]
Given that we tested robometry with downstream projects, could it make sense to start doing a release so we could merge this PR also with the changes in `LatestReleases.yaml` ? It does not need to be a 1.0.0, it can also be a 0.9.0 or similar.

**Comment by Nicogene** [comment]
I did the release of robometry (https://github.com/robotology/robometry/releases/tag/v1.0.0) and I change `latest.release.yml` here: https://github.com/robotology/robotology-superbuild/pull/1111/commits/28ee3f1ef9c0166ae9f6ba588f52cc919940da50

**Comment by traversaro** [comment]
Thanks!

**Review by traversaro — APPROVED** [review]

**Comment by Nicogene** [comment]
The errors are:

```
/home/runner/work/robotology-superbuild/robotology-superbuild/src/HumanDynamicsEstimation/devices/HumanStateProvider/HumanStateProvider.cpp:320:26: error: 'class yarp::os::Bottle' has no member named 'addVocab'; did you mean 'addVocab32'?
  320 |                 response.addVocab(yarp::os::Vocab::encode("many"));
      |                          ^~~~~~~~
      |                          addVocab32
```
Then I think unrelated to the robometry, shall we merge @traversaro ?

**Comment by traversaro** [comment]
> Then I think unrelated to the robometry, shall we merge @traversaro ?

I am afraid we did not reach a consensus on how to handle this: https://github.com/robotology/robotology-superbuild/issues/1127#issuecomment-1135497520 . I think we can quickly align in person.

**Comment by Nicogene** [comment]
After a T2T meeting, we decided for keeping both `YARP_telemetry` and `robometry` for the release coming in few days (v2022.05.0). 
I restored the `YARP_telemetry` references pointing to the last stable release (v0.5.1)

**Review by traversaro — APPROVED** [review]

**Pull request merged**
