### PR TITLE
Bump iDynTree version to v2.0.0 in 2020.11 distro

### PR DESCRIPTION
**Pull request by traversaro**
See https://github.com/robotology/idyntree/releases/tag/v2.0.0 .

### CODE REVIEW

**Review by Nicogene — APPROVED** [review]

**Comment by traversaro** [comment]
The macOS failures are expected due to , while the `[Tags:Release202011@windows-2019@Release]` is fishy and may indicate a regression caused by iDynTree 2 in one of the subprojects that has been solved in the master version, as `[Tags:Default@windows-2019@Release]` is passing fine.

**Comment by traversaro** [comment]
Indeed there is a failure on walking-controllers due to the problem in https://github.com/robotology/walking-controllers/pull/62 that is not part of a release.  I opened the issue https://github.com/robotology/walking-controllers/issues/70 for this.

**Comment by traversaro** [comment]
> 
> 
> Indeed there is a failure on walking-controllers due to the problem in [robotology/walking-controllers#62](https://github.com/robotology/walking-controllers/pull/62) that is not part of a release. I opened the issue [robotology/walking-controllers#70](https://github.com/robotology/walking-controllers/issues/70) for this.

Fixed by https://github.com/robotology/walking-controllers/releases/tag/v0.3.3 . I bumped the version in https://github.com/robotology/robotology-superbuild/pull/530/commits/53f6e7109473acadd934aa88c7bb8d3ca646cc9d . The old version by the way was quite old.

**Comment by GiulioRomualdi** [comment]
the walking-controllers is still failing with  (on ubuntu 20.04)
```
[ 17%] Building CXX object src/SimplifiedModelControllers/CMakeFiles/SimplifiedModelControllers.dir/src/DCMModelPredictiveController.cpp.o
In file included from /home/runner/work/robotology-superbuild/robotology-superbuild/robotology/walking-controllers/src/SimplifiedModelControllers/src/DCMModelPredictiveController.cpp:17:
/home/runner/work/robotology-superbuild/robotology-superbuild/build/install/include/iDynTree/Core/EigenSparseHelpers.h:14:10: fatal error: Eigen/SparseCore: No such file or directory
   14 | #include <Eigen/SparseCore>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by traversaro** [comment]
> 
> 
> the walking-controllers is still failing with (on ubuntu 20.04)
> 
> ```
> [ 17%] Building CXX object src/SimplifiedModelControllers/CMakeFiles/SimplifiedModelControllers.dir/src/DCMModelPredictiveController.cpp.o
> In file included from /home/runner/work/robotology-superbuild/robotology-superbuild/robotology/walking-controllers/src/SimplifiedModelControllers/src/DCMModelPredictiveController.cpp:17:
> /home/runner/work/robotology-superbuild/robotology-superbuild/build/install/include/iDynTree/Core/EigenSparseHelpers.h:14:10: fatal error: Eigen/SparseCore: No such file or directory
>    14 | #include <Eigen/SparseCore>
>       |          ^~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```

That is quite strange, as instead the Default job that uses Stable branches (i.e. walking-controllers master) is compiling fine.

**Comment by traversaro** [comment]
As discussed with @GiulioRomualdi in chat, walking-controllers probably still have some missing `Eigen3::Eigen` targets missing.

**Comment by traversaro** [comment]
> 
> 
> As discussed with @GiulioRomualdi in chat, walking-controllers probably still have some missing `Eigen3::Eigen` targets missing.

It turns out that this was a bug in osqp-eigen v0.5.2, that is fixed in the latest release v0.6.2, so we just bumped it.

**Comment by GiulioRomualdi** [comment]
Windows is now failing because of 
```
2020-11-24T11:55:41.1381343Z C:\robotology\robotology\include\iDynTree/Core/AngularMotionVector3.h(14,1): fatal error C1021: invalid preprocessor command 'warning' [D:\a\robotology-superbuild\robotology-superbuild\build\robotology\WBToolbox\toolbox\base\WBToolboxBase.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\WBToolbox.vcxproj]
```

**Comment by GiulioRomualdi** [comment]
https://github.com/robotology/wb-toolbox/pull/191 in wbd fixes the problem. However it has not be added in the latest wbd release. We may think to release it no?

**Comment by traversaro** [comment]
> 
> 
> [robotology/wb-toolbox#191](https://github.com/robotology/wb-toolbox/pull/191) in wbd fixes the problem. However it has not be added in the latest wbd release. We may think to release it no? @diegoferigo

I agree. We can release v5.2.1 or v5.3, let us know what do you prefer @diegoferigo or if you need any help, thanks!

**Comment by diegoferigo** [comment]
Done https://github.com/robotology/wb-toolbox/releases/tag/v5.3

**Comment by traversaro** [comment]
The only missing builds are the macOS ones, that are failing for other issues, so let's merge this.

**Pull request merged**
