### PR TITLE
Updated the workflow for building docker images on release

### PR DESCRIPTION
**Pull request by valegagge**
this PR contains the following changes:
- renamed the workflow `icubTechIIT_code.yml` in `build-docker-images.yml` 
- updated the repo of the repository dispatch action
- updated the git hub secrets.

cc @pattacini

### CODE REVIEW

**Comment by traversaro** [comment]
For reference, this Action is useful to trigger jobs in https://github.com/icub-tech-iit/docker-deployment-images .

**Review by traversaro — APPROVED** [review]

**Review by pattacini — APPROVED** [review]

**Comment by pattacini** [comment]
Fine ✅ 
I've updated the GH App credentials, thus we may need some testing.

**Comment by traversaro** [comment]
> I've updated the GH App credentials, thus we may need some testing.

Ok, is this ready for merge or not?

**Comment by pattacini** [comment]
>Ok, is this ready for merge or not?

I think so.

**Pull request merged**
