### PR TITLE
Add dependency of walking-controllers on bipedal-locomotion-framework

### PR DESCRIPTION
**Pull request by traversaro**
As `bipedal-locomotion-framework` is only compiled if `ROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS` component is enabled, to make sure that everything works as expected we need to move `walking-controllers` under the `DYNAMICS_FULL_DEPS` component.

Fix https://github.com/robotology/robotology-superbuild/issues/1010 .

### CODE REVIEW

**Comment by traversaro** [comment]
The dependency on BipedalLocomotionFramework was added in https://github.com/robotology/walking-controllers/pull/97, not sure why it started to fail just now.

**Comment by traversaro** [comment]
> The dependency on BipedalLocomotionFramework was added in [robotology/walking-controllers#97](https://github.com/robotology/walking-controllers/pull/97), not sure why it started to fail just now.

The reason is that we were using the `master` branch of  `walking-controllers` so we were not testing  `walking-controllers`'s `devel`, see https://github.com/robotology/robotology-superbuild/pull/1014

**Review by lrapetti — APPROVED** [review]
Thanks for the fix @traversaro (I have just experienced this issue)

**Comment by traversaro** [comment]
> Thanks for the fix @traversaro (I have just experienced this issue)

Thanks for the review, merging now.

**Pull request merged**
