### PR TITLE
Add <superbuild_install_prefix>/share to XDG_DATA_DIRS environment variable to support yarp bash autocompletion out of the box

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/robotology-superbuild/issues/622 .

### CODE REVIEW

**Review by S-Dafarra — APPROVED** [review]
Cool! Does it work also on Windows?

**Comment by traversaro** [comment]
> 
> 
> Cool! Does it work also on Windows?

I did not tested it, but it could work assuming that you installed `bash-completion` and you use Git Bash. However, in any  case I prefer to set `XDG_DATA_DIRS`  coherently across all platforms as this env variable could also affect other software.

**Comment by traversaro** [comment]
> 
> 
> > Cool! Does it work also on Windows?
> 
> I did not tested it, but it could work assuming that you installed `bash-completion` and you use Git Bash. However, in any case I prefer to set `XDG_DATA_DIRS` coherently across all platforms as this env variable could also affect other software.

If Instead you were referring to to the Powershell-based autocomplete (https://github.com/robotology/yarp/tree/master/data/WindowsPowerShell) I still need to check how to integrate it.

**Comment by traversaro** [comment]
I tested on a real Ubuntu 20.04 box and it seems to work fine!

**Pull request merged**
