### PR TITLE
Update latest.releases.yaml to `icub-firmware-models@v1.25.0`

### PR DESCRIPTION
**Pull request by pattacini**
As per the title.

### CODE REVIEW

**Review by Nicogene — APPROVED** [review]
LGTM but maybe we have to await https://github.com/robotology/robotology-superbuild/pull/1129?

**Comment by Nicogene** [comment]
I manually updated also `icub-firmware` and `icub-firmware-build` since they are not automatically updated by the GA

**Comment by pattacini** [comment]
> I manually updated also `icub-firmware` and `icub-firmware-build` since they are not automatically updated by the GA

Ah didn't know about that, thus I updated manually the `icub-firmware-shared` too.
Hope this won't cause trouble.

**Comment by Nicogene** [comment]
> > I manually updated also `icub-firmware` and `icub-firmware-build` since they are not automatically updated by the GA
> 
> Ah didn't know about that, thus I updated manually the `icub-firmware-shared` too. Hope this won't cause trouble.

I should be not, the version is automatically updated by those repo that compiles, for example icub-firmware does not then we have to remember to update it manually

**Comment by traversaro** [comment]
Thanks, merging as all failures are due to:
* https://github.com/robotology/robotology-superbuild/issues/1133
* https://github.com/robotology/robotology-superbuild/issues/1134

Not related to this PR.

**Pull request merged**
