### PR TITLE
Set default of ROBOTOLOGY_PROJECT_TAGS to Custom and fix release problems

### PR DESCRIPTION
**Pull request by traversaro**
Otherwise `ROBOTOLOGY_PROJECT_TAGS_CUSTOM_FILE` is ignored, for future reference this is necessary for all the `releases/*` branches, i.e. https://github.com/robotology/robotology-superbuild/pull/350 is incomplete.

### CODE REVIEW

**Comment by traversaro** [comment]
Actually running this in CI is more complicated then expected. The problem is that  in the current GitHub Actions scripts, the `ROBOTOLOGY_PROJECT_TAGS` is being overridden by the https://github.com/robotology/robotology-superbuild/blob/061bfba8c6aef07bd7d2a7ed9192e313d187acaf/.github/workflows/ci.yml#L117 and https://github.com/robotology/robotology-superbuild/blob/061bfba8c6aef07bd7d2a7ed9192e313d187acaf/.github/workflows/ci.yml#L132 . Probably the best solution for now is to remove that part in the `releases/2020.02` branch, and then think for 2020.05 a more permanent solution.

**Comment by traversaro** [comment]
Great, the CI is finally failing so it means that is actually running. : )

**Comment by traversaro** [comment]
> Great, the CI is finally failing so it means that is actually running. : )

There was a problem in the icub-gazebo URL, fixed by https://github.com/robotology/robotology-superbuild/commit/2b958f9b854ca1425a37085a5300aa986180a683 .

**Comment by traversaro** [comment]
Ok, finally some real problems that we did not have on `master` branches: 
~~~
2020-02-21T13:20:15.3104374Z D:\a\robotology-superbuild\robotology-superbuild\robotology\human-dynamics-estimation\devices\HumanStateProvider\InverseVelocityKinematics\InverseVelocityKinematics.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj [D:\a\robotology-superbuild\robotology-superbuild\build\robotology\human-dynamics-estimation\devices\HumanStateProvider\HumanStateProvider.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\build\human-dynamics-estimation.vcxproj]
~~~
This is due to https://github.com/robotology/human-dynamics-estimation/pull/174 and https://github.com/robotology/human-dynamics-estimation/issues/171#issuecomment-581007489 , and the fix is apparently not provided in `v2.0.0`. Can we tag a new version `v2.0.1` containing this fix? @lrapetti @Yeshasvitvs 

~~~
2020-02-21T13:15:59.2609392Z   CMake Error at C:/robotology/vcpkg/scripts/buildsystems/vcpkg.cmake:195 (_add_library):
2020-02-21T13:15:59.2609926Z     Target "UnicyclePlanner" links to target "OsqpEigen::OsqpEigen" but the
2020-02-21T13:15:59.2610227Z     target was not found.  Perhaps a find_package() call is missing for an
2020-02-21T13:15:59.2610478Z     IMPORTED target, or an ALIAS target is missing?
2020-02-21T13:15:59.2613476Z   Call Stack (most recent call first):
2020-02-21T13:15:59.2613765Z     CMakeLists.txt:93 (add_library)
2020-02-21T13:15:59.2614189Z   
2020-02-21T13:15:59.2614779Z   
2020-02-21T13:15:59.2615023Z   CMake Error at C:/robotology/vcpkg/scripts/buildsystems/vcpkg.cmake:195 (_add_library):
2020-02-21T13:15:59.2615262Z     Target "UnicyclePlanner" links to target "osqp::osqp" but the target was
2020-02-21T13:15:59.2617445Z     not found.  Perhaps a find_package() call is missing for an IMPORTED
2020-02-21T13:15:59.2617837Z     target, or an ALIAS target is missing?
2020-02-21T13:15:59.2618081Z   Call Stack (most recent call first):
2020-02-21T13:15:59.2618321Z     CMakeLists.txt:93 (add_library)
~~~
This is https://github.com/robotology/unicycle-footstep-planner/issues/33 . It has been fixed in iDynTree in https://github.com/robotology/idyntree/pull/642, but the fix is not part of iDynTree v1.0.1 . @traversaro can you please tag a v1.0.2 with this fix?

**Comment by traversaro** [comment]
>  @traversaro can you please tag a v1.0.2 with this fix?

Done in https://github.com/robotology/idyntree/pull/650 .

**Comment by Yeshasvitvs** [comment]
@traversaro we updated the master branch with the latest changes in devel following the PR https://github.com/robotology/human-dynamics-estimation/pull/164. 

After the [CI checks are done](https://travis-ci.org/robotology/human-dynamics-estimation/builds/653478582?utm_source=github_status&utm_medium=notification), we will tag the master with `v2.1.0` as the secondary calibration is more of a new feature than a patch.

@lrapetti

**Comment by traversaro** [comment]
> After the CI checks are done, we will tag the master with v2.1.0 as the secondary calibration is more of a new feature than a patch.

The CI checks seems to have a failure, but related to the deployment of the documentation, not of the library itself, so if you could tag v2.1.0 it would be great.

**Comment by traversaro** [comment]
> 
> 
> > After the CI checks are done, we will tag the master with v2.1.0 as the secondary calibration is more of a new feature than a patch.
> 
> The CI checks seems to have a failure, but related to the deployment of the documentation, not of the library itself, so if you could tag v2.1.0 it would be great.

fyi @lrapetti @Yeshasvitvs

**Comment by Yeshasvitvs** [comment]
@traversaro 

https://github.com/robotology/human-dynamics-estimation/releases/tag/v2.1.0

**Comment by traversaro** [comment]
> 
> 
> @traversaro
> 
> https://github.com/robotology/human-dynamics-estimation/releases/tag/v2.1.0

Thanks! Just to understand, at the  CMake level the version is still  2.0.0 (See https://github.com/robotology/human-dynamics-estimation/blob/269a08c2a282f87da3dad788e31b502ccc542409/CMakeLists.txt#L8) , this is not a big problem, but it may be confusing for downstream projects if they actually want to enforce the dependencny on 2.1.0 and its new features.

**Comment by Yeshasvitvs** [comment]
@traversaro The version of `OsqpEigen` is updated from `v0.4.0` to [v0.5.2](https://github.com/robotology/robotology-superbuild/blob/releases/2020.02/releases/2020.02.yaml#L77) for robotology 2020.02 release. However, inside HDE, the version referred to was v0.4.0 https://github.com/robotology/human-dynamics-estimation/blob/v2.1.0/devices/HumanStateProvider/CMakeLists.txt#L7. Didn't this result in any build issues during CI ?

**Comment by traversaro** [comment]
> 
> 
> @traversaro The version of `OsqpEigen` is updated from `v0.4.0` to [v0.5.2](https://github.com/robotology/robotology-superbuild/blob/releases/2020.02/releases/2020.02.yaml#L77) for robotology 2020.02 release. However, inside HDE, the version referred to was v0.4.0 https://github.com/robotology/human-dynamics-estimation/blob/v2.1.0/devices/HumanStateProvider/CMakeLists.txt#L7. Didn't this result in any build issues during CI ?

The compatibility rule is defined in OsqpEigen, and in the update from 0.4 to 0.5.2 the compatibility rules has changed to `SameMajorVersion` in https://github.com/robotology/osqp-eigen/commit/a349543cc2ac567a42579683f8ad3b4ca69d1f2e, so if the version requested is 0.4.0, 0.5.2 results as compatible.

**Pull request merged**
