### PR TITLE
When ROBOTOLOGY_PROJECT_TAGS is set to Unstable use devel walking-controllers branch

### PR DESCRIPTION
**Pull request by traversaro**
Before this PR the `master` branch was used, hiding problems such as the one catched (only when it reached the `Stable`/`master` branch) in https://github.com/robotology/robotology-superbuild/pull/1013 .

### CODE REVIEW

**Comment by traversaro** [comment]
@GiulioRomualdi @S-Dafarra I opened this as I saw the master/devel pattern used in walking-controllers, if you want to switch to the single `master` branch also for walking-controllers please reply, so we do not merge this PR.

**Comment by GiulioRomualdi** [comment]
Now also walking controller in master depends on blf.

**Comment by S-Dafarra** [comment]
> @GiulioRomualdi @S-Dafarra I opened this as I saw the master/devel pattern used in walking-controllers, if you want to switch to the single `master` branch also for walking-controllers please reply, so we do not merge this PR.

Since now ``master`` and ``devel`` are aligned we can also move to the pattern release/``master``. What do you think?

**Comment by traversaro** [comment]
> > @GiulioRomualdi @S-Dafarra I opened this as I saw the master/devel pattern used in walking-controllers, if you want to switch to the single `master` branch also for walking-controllers please reply, so we do not merge this PR.
> 
> Since now `master` and `devel` are aligned we can also move to the pattern release/`master`. What do you think?

That is fine for me.

**Comment by GiulioRomualdi** [comment]
I also agree to keep only master.

**Comment by traversaro** [comment]
Ok!

**Pull request closed without merging**
