### PR TITLE
Add icub-tests repository

### PR DESCRIPTION
**Pull request by diegoferigo**
This PR adds the [`icub-tests`](https://github.com/robotology/icub-tests) repository to the superbuild. I'm not yet sure that the `CORE` profile is the best location, let me know what you think.

Closes https://github.com/robotology/robotology-superbuild/issues/3.

Blocked by https://github.com/robotology/icub-tests/pull/41.

cc @traversaro

### CODE REVIEW

**Comment by traversaro** [comment]
I guess it will be `CORE`, unless someone proposes a better solution before the merge.

**Comment by traversaro** [comment]
Travis is failing because robotology-superbuild is still using GCC 4.8 . Opening a PR for that now.

**Comment by diegoferigo** [comment]
Done thanks!

**Comment by traversaro** [comment]
Merged, thanks!

**Pull request merged**
