### PR TITLE
Add portaudio dependency and enable audio-related devices in YARP

### PR DESCRIPTION
**Pull request by traversaro**
This PR add the dependency on portaudio on Linux, macOS and Windows, and enable by default the compilation of the YARP devices related to audio. Fix https://github.com/robotology/robotology-superbuild/issues/284 .

### CODE REVIEW

**Comment by traversaro** [comment]
For the members of iCub Tech's Team Code, this PR will mean that from 2020.11 the audio support of YARP should also be directly available in robot-bazaar's Docker images. @vtikha @AlexAntn @ilaria-carlini

**Comment by traversaro** [comment]
Note that this PR may fail for Windows/Unstable as https://github.com/robotology/ycm/pull/357 still needs to be propagated to the master branch of ycm, but for that we just need to wait one day.

**Comment by traversaro** [comment]
There are a few open problems.

The Windows compilation is still failing, mainly because we were still using YCM 0.11 as a stable branch, this was fixed in https://github.com/robotology/robotology-superbuild/pull/499/commits/9e1fb78dc5d2867619a0a81979c12af4a14a2d8f .

Other problems include:

### macOS
On macOS, the configuration fails with:
~~~
CMake Error at /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/SelectLibraryConfigurations.cmake:71 (set):
  Syntax error in cmake code at

    /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/SelectLibraryConfigurations.cmake:71

  when parsing string

    ${PortAudio_-FRAMEWORK COREAUDIO_LIBRARY}

  Invalid character (' ') in a variable name: 'PortAudio_-FRAMEWORK'
Call Stack (most recent call first):
  /Users/runner/work/robotology-superbuild/robotology-superbuild/build/install/share/YCM/modules/StandardFindModule.cmake:153 (select_library_configurations)
  /Users/runner/work/robotology-superbuild/robotology-superbuild/build/install/share/YCM/find-modules/FindPortAudio.cmake:31 (standard_find_module)
  cmake/YarpFindDependencies.cmake:379 (find_package)
  CMakeLists.txt:61 (include)
~~~

### Releases

The currently tested release (2020.05 and 2020.08) will be broken as they will not have the necessary fixes in their YCM version. As the 2020.11 release is fast approaching, I think we can simply drop these releases from the `master` branch CIs (anyone that uses them can simply use the related tags) and add the 2020.11 release instead.

**Comment by traversaro** [comment]
The macOS problem is due to the fact that `portaudio-2.0` pkg-config file structure is: 
~~~
Mac-1603138180646:build runner$ cat /usr/local/lib/pkgconfig/portaudio-2.0.pc
prefix=/usr/local/Cellar/portaudio/19.6.0
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: PortAudio
Description: Portable audio I/O
Requires:
Version: 19

Libs: -L${libdir} -lportaudio -framework CoreAudio -framework AudioToolbox -framework AudioUnit -framework Carbon
Cflags: -I${includedir}
Mac-1603138180646:build runner$
~~~

and probably the YCM's `standard_find_module` is not able to deal with the `-framework` options passed as part of `Libs`.

**Comment by traversaro** [comment]
Additional macOS-related fixes: 
* https://github.com/robotology/ycm/pull/358
* https://github.com/robotology/yarp/pull/2387

**Comment by traversaro** [comment]
> 
> 
> Additional macOS-related fixes:
> 
>     * [robotology/ycm#358](https://github.com/robotology/ycm/pull/358)
> 
>     * [robotology/yarp#2387](https://github.com/robotology/yarp/pull/2387)

As this PR have been merged and I bumper the commits of YARP and YCM in the 2020.11 release, I think the PR is finally ready to be merged.

**Review by S-Dafarra — APPROVED** [review]

**Pull request merged**
