### PR TITLE
Update scripts and documentation to set environment variables necessary to correctly load meshes in URDF and SDF files

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/robotology-superbuild/issues/577 . `GAZEBO_MODEL_PATH`  has been defined also if `ROBOTOLOGY_USES_GAZEBO` is not enabled, as the `icub-models`-installed models are installed in any case, and also software different from Gazebo may need to load them.

### CODE REVIEW

**Comment by traversaro** [comment]
By the way, I wonder how the RViz-based visualizer for human dynamics was working without this @Yeshasvitvs @lrapetti . You set the `ROS_PACKAGE_PATH`  manually?

**Comment by Yeshasvitvs** [comment]
> You set the ROS_PACKAGE_PATH manually?

Yes, [install location](https://github.com/robotology/human-dynamics-estimation/blob/master/conf/CMakeLists.txt#L44-L69) of [HDE ROS configuration files](https://github.com/robotology/human-dynamics-estimation/tree/master/conf/ros) is manually added to `ROS_PACKAGE_PATH` in `bashrc`

**Comment by traversaro** [comment]
> 
> 
> > You set the ROS_PACKAGE_PATH manually?
> 
> Yes, [install location](https://github.com/robotology/human-dynamics-estimation/blob/master/conf/CMakeLists.txt#L44-L69) of [HDE ROS configuration files](https://github.com/robotology/human-dynamics-estimation/tree/master/conf/ros) is manually added to `ROS_PACKAGE_PATH` in `bashrc`

Was this documented somewhere? After this PR, it should not be necessary anymore, so it may be worth to update those docs.

**Comment by traversaro** [comment]
> 
> 
> > You set the ROS_PACKAGE_PATH manually?
> 
> ~Yes, [install location](https://github.com/robotology/human-dynamics-estimation/blob/master/conf/CMakeLists.txt#L44-L69) of [HDE ROS configuration files](https://github.com/robotology/human-dynamics-estimation/tree/master/conf/ros) is manually added to `ROS_PACKAGE_PATH` in `bashrc`~
> 
> **Update:** Yes, the current setup I have is to manually add `export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:${ROBOTOLOGY_SUPERBUILD_INSTALL_PREFIX}/share` to `bashrc`, and install [HDE ROS configuration files](https://github.com/robotology/human-dynamics-estimation/blob/master/conf/CMakeLists.txt#L44-L69) and other support files like [human-gazebo](https://github.com/robotology/human-gazebo/blob/master/CMakeLists.txt#L22-L26).

Please don't update older comments without commenting again the thread, as if you do like that people partecipating in the discussion don't get notifications for your new edits.

**Comment by traversaro** [comment]
Friendly ping @GiulioRomualdi @S-Dafarra, this is necessary for ensuring the iDynTree visualiser works out of the box.

**Comment by traversaro** [comment]
Failures are not related and can be safely ignored.

**Review by S-Dafarra — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @S-Dafarra !

**Pull request merged**
