### PR TITLE
Bump version of YCM to the version with the latest ExternalProject

### PR DESCRIPTION
**Pull request by traversaro**
We typically do not depend on `devel` branches of subpackages, but the change in https://github.com/robotology/ycm/pull/188 is quite massive, and it will probably not undergo further testing before YCM 0.10 . Let's just bootstrap the commit from the latest `devel` version of YCM now, so if any major error emerges we can catch it fast, instead of waiting for YCM 0.10 release.

### CODE REVIEW

**Comment by traversaro** [comment]
Waiting for CI on this.

**Comment by traversaro** [comment]
Failure in Travis:
~~~
Cloning into 'YCM'...
Note: checking out 'ae7e854a593bf13f48c67ecd3af4b2b23d79bd9c'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
HEAD is now at ae7e854... Merge pull request #188 from drdanz/ExternalProject_sync
-- Performing update step for 'YCM'
-- Performing configure step for 'YCM'
Not searching for unused variables given on the command line.
loading initial cache file <TMP_DIR>/YCM-cache-$<CONFIG>.cmake
CMake Error: Error processing file: <TMP_DIR>/YCM-cache-$<CONFIG>.cmake
CMake Error: The source directory "/home/travis/build/robotology/robotology-superbuild/build/robotology/YCM/<SOURCE_DIR><SOURCE_SUBDIR>" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
CMake Error at build/CMakeFiles/YCMEPHelper.cmake:1335 (message):
  Cannot configure YCM repository
Call Stack (most recent call first):
  cmake/YCMBootstrap.cmake:107 (ycm_bootstrap)
  CMakeLists.txt:106 (include)
~~~
failure on my Bionic machine:
~~~
-- Performing configure step for 'YCM'
Not searching for unused variables given on the command line.
loading initial cache file /home/straversaro/src/robotology-superbuild/build/robotology/YCM/CMakeFiles/YCMTmp/YCM-cache.cmake
-- YCM Version: 0.9.20190214.7-20190214.7+gitae7e854 (0.9.20190214.7)
CMake Error at cmake-next/master/CMakePackageConfigHelpers.cmake:236 (message):
  Unknown keywords given to CONFIGURE_PACKAGE_CONFIG_FILE():
  "CMAKE_CACHE_DEFAULT_ARGS/share/YCM/cmake"
Call Stack (most recent call first):
  CMakeLists.txt:93 (configure_package_config_file)


-- Configuring incomplete, errors occurred!
~~~

**Comment by traversaro** [comment]
On the other hand, non-bootstrapped YCM devel used with the robotology-superbuild works fine.

**Comment by traversaro** [comment]
@drdanz Did you saw this? To be honest I did not looked into it.

**Comment by drdanz** [comment]
> @drdanz Did you saw this?
Nope :smile:
I'll have a look...

**Comment by traversaro** [comment]
I can confirm that is failing also on my local system, with the following verbose output: 
~~~
traversaro@turati:~/src/robotology-superbuild/build$ cmake -DYCM_BOOTSTRAP_VERBOSE:BOOL=ON .
-- YCM not found. Bootstrapping it.
-- Downloading YCMEPHelper.cmake - Attempt 1 of 3
-- Downloading YCMEPHelper.cmake - SUCCESS
-- Downloading StyleGITHUB.cmake - Attempt 1 of 3
-- Downloading StyleGITHUB.cmake - SUCCESS
-- Performing download step (git clone) for 'YCM'
-- Avoiding repeated git clone, stamp file is up to date: '/home/traversaro/src/robotology-superbuild/build/robotology/YCM/CMakeFiles/YCMStamp/YCM-gitclone-lastrun.txt'
-- Performing update step for 'YCM'
-- Performing configure step for 'YCM'
Not searching for unused variables given on the command line.
loading initial cache file /home/traversaro/src/robotology-superbuild/build/robotology/YCM/CMakeFiles/YCMTmp/YCM-cache.cmake
-- YCM Version: 0.9.20190214.7-20190214.7+gitae7e854 (0.9.20190214.7)
CMake Error at cmake-next/master/CMakePackageConfigHelpers.cmake:236 (message):
  Unknown keywords given to CONFIGURE_PACKAGE_CONFIG_FILE():
  "CMAKE_CACHE_DEFAULT_ARGS/share/YCM/cmake"
Call Stack (most recent call first):
  CMakeLists.txt:93 (configure_package_config_file)


-- Configuring incomplete, errors occurred!
See also "/home/traversaro/src/robotology-superbuild/build/robotology/YCM/CMakeFiles/CMakeOutput.log".
CMake Error at build/CMakeFiles/YCMEPHelper.cmake:1335 (message):
  Cannot configure YCM repository
Call Stack (most recent call first):
  cmake/YCMBootstrap.cmake:107 (ycm_bootstrap)
  CMakeLists.txt:106 (include)


-- Configuring incomplete, errors occurred!
See also "/home/traversaro/src/robotology-superbuild/build/CMakeFiles/CMakeOutput.log".
See also "/home/traversaro/src/robotology-superbuild/build/CMakeFiles/CMakeError.log".
~~~

**Comment by traversaro** [comment]
Updating to the latest YCMBootstrap and IncludeUrl files, the error is: 
~~~
traversaro@turati:~/src/robotology-superbuild/build$ cmake -DYCM_BOOTSTRAP_VERBOSE:BOOL=ON .
-- YCM not found. Bootstrapping it.
-- Downloading YCMEPHelper.cmake - Attempt 1 of 3
-- Downloading YCMEPHelper.cmake - SUCCESS
-- Downloading StyleGITHUB.cmake - Attempt 1 of 3
-- Downloading StyleGITHUB.cmake - SUCCESS
-- Performing download step (git clone) for 'YCM'
-- Avoiding repeated git clone, repository already exists
-- Performing update step for 'YCM'
fatal: ambiguous argument 'devel': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD is up to date.
-- Performing configure step for 'YCM'
Not searching for unused variables given on the command line.
loading initial cache file <TMP_DIR>/YCM-cache-$<CONFIG>.cmake
CMake Error: Error processing file: <TMP_DIR>/YCM-cache-$<CONFIG>.cmake
CMake Error: The source directory "/home/traversaro/src/robotology-superbuild/build/robotology/YCM/<SOURCE_DIR><SOURCE_SUBDIR>" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
CMake Error at build/CMakeFiles/YCMEPHelper.cmake:1345 (message):
  Cannot configure YCM repository
Call Stack (most recent call first):
  cmake/YCMBootstrap.cmake:114 (ycm_bootstrap)
  CMakeLists.txt:105 (include)


-- Configuring incomplete, errors occurred!
See also "/home/traversaro/src/robotology-superbuild/build/CMakeFiles/CMakeOutput.log".
~~~

**Comment by drdanz** [comment]
Opened robotology/ycm#218

**Comment by traversaro** [comment]
[ycm-0.9.99.zip](https://github.com/robotology/robotology-superbuild/files/2996703/ycm-0.9.99.zip)

**Comment by drdanz** [comment]
The bootstrap should be fixed, please try again

**Comment by traversaro** [comment]
Locally everything is working, testing after the update of YCM's commit.

**Comment by drdanz** [comment]
I suggest to update also the local versions of YCMBootstrap.cmake and IncludeUrl.cmake

**Comment by traversaro** [comment]
> I suggest to update also the local versions of YCMBootstrap.cmake and IncludeUrl.cmake

Agreed, but I prefer to wait for a proper release to also require YCM 0.10 when YCM is installed, see https://github.com/robotology/robotology-superbuild/issues/189 .

**Comment by traversaro** [comment]
Not sure what is happening, but locally the PR is failing with this YCM Boostrap error: 
~~~
[ 98%] Files from build-modules installed in CMake build directory
[ 98%] Built target build-modules
[100%] Files from style-modules installed in CMake build directory
[100%] Built target style-modules
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/share/YCM/cmake/YCMConfigVersion.cmake
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/home/straversaro/src/robotology-superbuild/build3/robotology/YCM/YCMConfigVersion.cmake"
  to "/usr/local/share/YCM/cmake/YCMConfigVersion.cmake".


Makefile:116: recipe for target 'install' failed
make: *** [install] Error 1
CMake Error at build3/CMakeFiles/YCMEPHelper.cmake:1387 (message):
  Cannot install YCM
Call Stack (most recent call first):
  cmake/YCMBootstrap.cmake:114 (ycm_bootstrap)
  CMakeLists.txt:104 (include)


-- Configuring incomplete, errors occurred!
See also "/home/straversaro/src/robotology-superbuild/build3/CMakeFiles/CMakeOutput.log".
~~~

**Comment by traversaro** [comment]
> > I suggest to update also the local versions of YCMBootstrap.cmake and IncludeUrl.cmake
>
> Agreed, but I prefer to wait for a proper release to also require YCM 0.10 when YCM is installed, see https://github.com/robotology/robotology-superbuild/issues/189 .

Done in  https://github.com/robotology/robotology-superbuild/pull/175/commits/07de4a56a510d4df1417ea8813bee0045a220089

**Comment by drdanz** [comment]
```
...
-- Installing: /usr/local/share/YCM/find-modules/FindAtlas.cmake
-- Installing: /usr/local/share/YCM/find-modules/FindCFW2CANAPI.cmake
...
```

Apparently, for some reason it is installing it in `/usr/local`

I think it might be because it is no longer reading the cache file :crying_cat_face:

**Comment by drdanz** [comment]
Hmm this is weird... It's not a problem of the cache, but the `CMAKE_PREFIX_PATH` is passed as
`-DCMAKE_PREFIX_PATH:PATH=<build>/robotology-superbuild/install|<YCM CMAKE_PREFIX_PATH>;` with a `|` in the middle. I suppose CMake does not recognise it as a path, and therefore use the default value

**Comment by traversaro** [comment]
Setting `CMAKE_PREFIX_PATH` changes the `CMAKE_INSTALL_PREFIX`?

**Comment by drdanz** [comment]
@traversaro should be fixed by robotology/ycm#231, can you please try again?

**Comment by drdanz** [comment]
> Setting `CMAKE_PREFIX_PATH` changes the `CMAKE_INSTALL_PREFIX`?

Sorry, I deleted the comment as soon as I realized that that was the wrong variable, but you are too fast! :rofl:

**Comment by traversaro** [comment]
This is now working fine.

**Comment by traversaro** [comment]
One Travis Job was fine, as what it is tested is not related to the choice of compiler, let's merge it.

**Pull request merged**
