### PR TITLE
Add workarounds to fix Homebrew CI

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/robotology-superbuild/issues/565 .

### CODE REVIEW

**Comment by traversaro** [comment]
The workaround is working. The Homebrew CI is now failing for another reason (that is currently tracked in https://github.com/osrf/homebrew-simulation/issues/1235), but I think we can merge this PR.

**Review by lrapetti — APPROVED** [review]

**Comment by traversaro** [comment]
I also added a workaround for https://github.com/osrf/homebrew-simulation/issues/1235 taken from https://github.com/ignition-tooling/release-tools/pull/366 .

**Comment by lrapetti** [comment]
> I also added a workaround for [osrf/homebrew-simulation#1235](https://github.com/osrf/homebrew-simulation/issues/1235) taken from [ignition-tooling/release-tools#366](https://github.com/ignition-tooling/release-tools/pull/366) .

Thanks @traversaro,
is the failure we see on macOS-11 related, or is it something new?

**Comment by traversaro** [comment]
> 
> 
> > I also added a workaround for [osrf/homebrew-simulation#1235](https://github.com/osrf/homebrew-simulation/issues/1235) taken from [ignition-tooling/release-tools#366](https://github.com/ignition-tooling/release-tools/pull/366) .
> 
> Thanks @traversaro,
> is the failure we see on macOS-11 related, or is it something new?

The failure affects both 10.15 and 11.0 . It is related to the latest Boost relaese on Homebrew (1.75, see https://github.com/osrf/homebrew-simulation/issues/1235).

**Comment by traversaro** [comment]
The only two failures are two network flakes, I think we can merge.

**Pull request merged**
